name: hello-world
on:
  push:
    branches:
      - '*'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 30
      - name: my-step
        run: echo "Hello World!"